### PR TITLE
split i2c_read into read and write_read

### PR DESCRIPTION
**Pull request by teamplayer3**
Using new esp-idf i2c interface, it is an error to use `write_read` with an empty send buffer. I split the read into single `read` and `read_write`. ~~I couldn't confirm if it works as it should after these changes.~~

### CODE REVIEW

**Comment by FloppyDisck** [comment]
Ill give it a look today, thanks for the PR

**Comment by dvdsk** [comment]
I tried this on my async [fork](https://github.com/dvdsk/SHT31-rs) as it wasnt working with embassy-stm32 and with work applied its now working :tada:

**Comment by dcampbell24** [comment]
This fixes the package for me too! I was going crazy with this not working. This is on a Raspberry Pi 5. Please, merge this fix.

**Review by FloppyDisck — APPROVED** [review]

**Comment by dcampbell24** [comment]
Can you make it so the commits don't have to be signed?

**Pull request merged**
